mixinText: |-
  mixin: # object
    tun:
      enable: true
      stack: gvisor # 或 gvisor
      dns-hijack: # DNS劫持设置为系统DNS
        - 119.29.29.29 # 可任意设置，但为了保证CFW关闭后能不影响联网，建议设置真实能访问的DNS服务器
      macOS-auto-route: true
      macOS-auto-detect-interface: true # 自动检测出口网卡
showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
interfaceName: en0
connProfile: true
connMode: true
connProxy: 2
proxyOrder: 0
